### ISSUE TITLE
Service Health Alert doesn't show a correct information.

### ISSUE THREAD

**Issue by kongou-ae** [Azure/reliability-workbook#100]
Hi, 

In my environment, Service Health Alert doesn't show a correct information.

The result of my workbook is as follows. Four categories are 0%.

![image](https://user-images.githubusercontent.com/3410186/231933785-a9ebc998-17fe-4bf2-8631-8435dc6ed4e6.png)

But this subscription has a service health alert which four categories are enabled.

![image](https://user-images.githubusercontent.com/3410186/231934054-b2464dcd-2670-44ad-aef5-519aecce8d1d.png)

Best regards

**Comment by kongou-ae** [comment]
I found a root cause.

Workbook of Service Health Alert uses the following kusto query to check the configuration of service health alert.

```
| extend incidentType = iff(isnull(properties.condition.allOf[1]), "All", properties.condition.allOf)
```

But If the combination of All event types and specific regions is used in a service health alert, `properties.condition.allOf[1]` is not null. then `incidentType` doesn't become `All`

```
        "condition": {
            "allOf": [
                {
                    "field": "category",
                    "equals": "ServiceHealth"
                },
                {
                    "field": "properties.impactedServices[*].ImpactedRegions[*].RegionName",
                    "containsAny": [
                        "Japan West",
                        "Japan East"
                    ]
                }
            ]
        },
```

Best regards.

**Comment by tsubasaxZZZ** [comment]
@kongou-ae Thank you for your cooperation! Also, I've been reproducing in my environment as well. We will address this soon.
