### ISSUE TITLE
The recommendation of public IP address is ambiguous.

### ISSUE THREAD

**Issue by kongou-ae** [Azure/reliability-workbook#101]
Hi,

The recommendation summary of public IP address shows the count of public IP address which is no Zone.

![image](https://user-images.githubusercontent.com/3410186/231947885-d1625796-4c2e-47ac-a1bb-c35a06fdd11d.png)

But the table of public IP address shows not only no zone but also single zone as error.

![image](https://user-images.githubusercontent.com/3410186/231948151-2999a732-fef4-4b03-b8f9-709502533410.png)

Which is a correct recommendation of this workbook?
- Public IP address should not be no zone. So, no zone is NG but single zone is OK. 
- Public IP address should be zone redundant. So, single zone and no zone are NG.

Best regards,

**Comment by tsubasaxZZZ** [comment]
We discussed and adopted the following rule:
> Public IP address should be zone redundant. So, single zone and no zone are NG.

The reason is that we want to be on the foolproof side. I understand PIP's redundancy depends on backend services, so choosing zone redundant isn't always the best choice. I hope there's a discussion to adopt the best architecture.

**Comment by tsubasaxZZZ** [comment]
Closed with v2.10(#148).
