### ISSUE TITLE
Will the reliability-workbook be added to WorkBooks in Monitor?

### ISSUE THREAD

**Issue by koudaiii** [Azure/reliability-workbook#102]
When you deploy the reliability-workbook from the [README](https://github.com/Azure/reliability-workbook/blob/main/README.md#reliability-workbook) using “Deploy to Azure”, it is added to WorkBooks in Monitor. This WorkBooks includes galleries such as performance and availability, making it intuitive and easy to understand.
![image](https://user-images.githubusercontent.com/2929102/232647271-411fcbee-aaed-4a6a-b790-3592d309c2e8.png)
![image](https://user-images.githubusercontent.com/2929102/232647318-179c6617-f5c0-4816-bee2-b26322c2e13a.png)

Currently, the reliability-workbook is available for preview in Advisor’s WorkBooks. In my opinion, it would be more user-friendly to transition from Monitor to WorkBooks rather than from Advisor to WorkBooks and then to the reliability-workbook. Is there a plan to add it?

![image](https://user-images.githubusercontent.com/2929102/232647361-99928424-0467-43fb-969c-fd5d56a82341.png)

**Comment by infosatheesh2020** [comment]
@koudaiii Reliability workbook falls under Well-Architected reliability pillar, and this surfaces best practices to the customers closing aligning with Advisor guidance (surface reliability best practices to users). Hence this is being published under Advisor workbooks gallery under Reliability category. This workbook doesn't strictly fall under monitoring or Operating excellence pillar of Well-Architected pillar and hence there this workbook might not be suitable to be part of Azure Monitor gallery. We are free to import it from GitHub.

**Comment by koudaiii** [comment]
Hi @infosatheesh2020 , I see. I understood your clear explanation and the breakdown of responsibilities. So this workbook goes into the Advisor workbook because it focuses on giving recommendations from a reliability perspective.

**Comment by koudaiii** [comment]
My issue has been resolved. I will close this issue now. 😄 
@tsubasaxZZZ @infosatheesh2020 Thank you for your reply 😄
