### ISSUE TITLE
Logic App is categorized App Service

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/reliability-workbook#13]
"type" field can use to idenfiy.
![image](https://user-images.githubusercontent.com/3822284/182322254-cdeefe18-06f3-4a2b-8473-ef6ec7f9f239.png)
![image](https://user-images.githubusercontent.com/3822284/182322308-87284db6-27c7-4df5-aac2-cdb65ce3c8ce.png)
![image](https://user-images.githubusercontent.com/3822284/182323085-351a3c47-8003-4898-8ba3-701bd083150b.png)

**Comment by infosatheesh2020** [comment]
Workbook auto categorizes based on RP. Need to explore for customization
