### ISSUE TITLE
Add measure of "State" to calculate AzFW score

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/reliability-workbook#14]
Current Reliability score doesn't include measure of "State" for calculating AzFW score.
So even if the resource state is failed, it's not impacted to score.
![image](https://user-images.githubusercontent.com/3822284/185065559-abac03ec-ae1a-4fa4-83eb-edfd2d21f3bc.png)

```kusto
// AzureFirewall - 1 check // score = (AZ) * 100 / (1 * ResourceTotal)
Type == 'microsoft.network/azurefirewalls', AvZoneCount * 100 / ResourceTotal,
```

**Comment by infosatheesh2020** [comment]
Fixed in v2.8
