### ISSUE TITLE
VM Classic showing in Advisor

### ISSUE THREAD

**Issue by cshea15** [Azure/reliability-workbook#16]
We had a customer who had VM Classic machines showing up in the Azure Advisor but under the Compute tab, no VM Classic VMs showed up. We believe it's because they have a Kubernetes cluster and those are the cluster nodes. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/58995422/187669633-b45c88d4-5b32-4b87-8cad-1350886403d3.png)

**Comment by infosatheesh2020** [comment]
Fixed in v2.8
