### ISSUE TITLE
New Front Door resource isn't shown

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/reliability-workbook#18]
On Front Door tabs, new Front Door resources isn't shown.
The reason that query is old resource type such as following:
```
type == "microsoft.network/frontdoors"
```

Following is New Front Door resource type:
```
Microsoft.Cdn/profiles
```

But if do query above, it might be mix old CDN profile.

**Comment by infosatheesh2020** [comment]
Fixed in v2.8
