### ISSUE TITLE
Azure PostGres support in workbook

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/reliability-workbook#43]
Database section to be enhanced with Azure database for Postgresql

**Comment by infosatheesh2020** [comment]
Picked by Jeff already

**Comment by tsubasaxZZZ** [comment]
@wjpigott Could you assign this issue your self?

**Comment by wjpigott** [comment]
@tsubasaxZZZ @infosatheesh2020  I dont think I can assign myself to this as I am not an owner/admin, I ready if I am marked as a collaborator on the repo that would work as well. Are you not able to assign it to me? Let me know if I am missing something.

**Comment by tsubasaxZZZ** [comment]
Closed by https://github.com/Azure/reliability-workbook/pull/135
