### ISSUE TITLE
Advisor feedback5: nested templates #16997080

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/reliability-workbook#48]
5)	I’d also suggest in the near future, [splitting this up in to several templates](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FApplication-Insights-Workbooks%2Fblob%2Fmaster%2FDocumentation%2FGroups%2FGroups.md%23how-to-split-a-large-template-into-many-templates&data=05%7C01%7CSatheeshkumar.Manoharan%40microsoft.com%7C935d759655c24b82b9d808daedf10d24%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638083916888330479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F%2BTvGyiHKVYZvHnZEbfa%2B40D5h2dmXrG92CKWLwgGpo%3D&reserved=0) so that each group is a template and loaded as necessary.
The template is almost 1mb in size.  That means every user downloads 1mb of json (compressed but still has to be decompressed+parsed) even if they only ever click on the second tab.
Usually with things this big we recommend the first tab (in your case probably also summary tab?) be in the “outer” template and each other tab be its own group that loads from another template.  Some teams make those nested templates also directly clickable in the gallery, so that if you only ever cared about storage, you could just open that template directly from the gallery instead of always clicking the storage tab.  The azure backup team did this and dramatically lowered the load time for its templates.  Many of the insights also do this as well.

**Comment by tsubasaxZZZ** [comment]
We can refer [this part](https://github.com/microsoft/Application-Insights-Workbooks/blob/9c6004608f674fed0f8bb43d2a2f22d5f67a2dfa/Workbooks/Azure%20Backup/Backup%20Report/Backup%20Report.workbook#L812) of Azure Backup. Workbook to be loaded must be under ["Workbooks"](https://github.com/microsoft/Application-Insights-Workbooks/tree/9c6004608f674fed0f8bb43d2a2f22d5f67a2dfa/Workbooks) on GitHub directory.

**Comment by tsubasaxZZZ** [comment]
- [ ] Verify that "Deploy to Azure" is working properly
- [ ] Verify that each pane shows or not when turn on/off "Show SLA" and "Show Help"
