### ISSUE TITLE
AKS when VMSS is put in different RG

### ISSUE THREAD

**Issue by colincole** [Azure/reliability-workbook#5]
For scenarios where AKS is blackened by VMSS (the default), but the VMSS gets put into a resource group outside of the default location (this is the behavior of Enterprise Scale Landing Zone AKS Accelerator). When this happens, the AvailabilitySet column of 3rd spreadsheet shows that "scale sets not configured" and shows capacity = 0, when in fact capacity is not zero and scale sets are configured. Basically we're not looking for the VMSS in the right location in this scenario. This is easily replicated by running the ES LZ AKS Accelerator.

**Comment by tsubasaxZZZ** [comment]
Even if the cluster is using default Resource Group, there is a pattern that is not working correctly like following.
> mc_rg-simpleaks0717a_aksdemo7u2te7-japaneast

```
| join kind = leftouter (
    resources 
    | where type == "microsoft.compute/virtualmachinescalesets"
    | extend aksname = tolower(tostring(split(resourceGroup, "_")[2])) <--------- 
    | extend AvZones = coalesce(tostring(array_length(parse_json(zones))), 'Not Configured'), AvSets = "Scale Sets"
    )
    on aksname
```
