### ISSUE TITLE
Using ZRS for storage should be considered resilient

### ISSUE THREAD

**Issue by colincole** [Azure/reliability-workbook#71]
For a storage account, it looks like the workbook currently requires GRS for a 100% on the resource. I would argue that ZRS should be considered resilient and 100%. Especially considering the new 3+0 regions don't have GRS as an option.  A customer yesterday called this out as well (they had their storage account set to ZRS and wanted to know why we had recommended improvements.

**Comment by wjpigott** [comment]
@tsubasaxZZZ  I worked this issue today to, I havent commited it as I didnt know if you want it in the  same PR as the other.  I changed the query to not count if it is zrs or ra-gzrs, and then changed a typo i think why the icons were not showing right. I added zrs to have a green icon so they can see that it is successful and shouldnt be counted in the other query. this is how it would look with my check in. 
![image](https://github.com/Azure/reliability-workbook/assets/86477713/9da4e89b-1530-4e79-8475-4046cd96c4f3)
@colincole let me know if that is what you understand from the customer as well.

**Comment by wjpigott** [comment]
@tsubasaxZZZ  I tested ra-gzrs as well and it is working as expected. I'll add this to the PR.  https://github.com/Azure/reliability-workbook/pull/135
![image](https://github.com/Azure/reliability-workbook/assets/86477713/7e148cc5-df95-45dd-8932-6ef8776115f3)

**Comment by tsubasaxZZZ** [comment]
Fixed by this commit: https://github.com/Azure/reliability-workbook/commit/0ee12965d3f1393c2b934cde94436169e9a6c5a7#diff-c33d3feec80eaecbc430617986aec9967a084ed12ea60e1b7864f162a04efd25
