### ISSUE TITLE
New feature: Check Network component

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/reliability-workbook#8]
- Public IP Address
  - Check SKU Basic
  - Check zonal if deployed supported zone region
- ER Gateway(Microsoft.Network/virtualNetworkGateways)
  - Check provisioningState
  - Check SKU(above Standard, use Az)
- VPN Gateway(Microsoft.Network/vpnGateways)
  - Check provisioningState
  - Check SKU(above Standard, use Az)
  - Check Active-Active

**Comment by infosatheesh2020** [comment]
"Microsoft.Network/vpnGateways" is legacy stuff. Need test data to implement.
